######################################################################################
###  __  __  ___  ____   ___  ____  ___                                            ###
### |  \/  ||_ _|| __ ) |_ _|| __ )|_ _|  ___                                      ###
### | |\/| | | | |  _ \  | | |  _ \ | |  / _ \                                     ###
### | |  | | | | | |_) | | | | |_) || | | (_) |                                    ###
### |_|  |_||___||____/ |___||____/|___| \___/                                     ###
###                                                                                ###
######################################################################################
# (MIBIBIO):Collection of microbial analysis workflows to investigate microbiological community structure, characteristics and their degradation potential.

project_metadata:
  name: "Griftpark Soilcore Analysis"
  author: "Simon"

paths:
  phyloseq_rds: "data/ps_taxid.final_with_tree.rds"
  metadata_txt: "data/Wetland_Recalculated_Metadata_Subselection_Analysis.txt"

scripts:
  #Preprocessing
  rarefaction: "scripts/02_rarefaction_curves.R"
  filtering: "scripts/02_filtering_prevalence_abundance.R"
  variance: "scripts/02_filtering_variance.R"
  normalization: "scripts/03_normalisation.R"
  # Barplots
  barplot_main: "scripts/08_barchart_visualisation_New.R"
  barplot_focus: "scripts/08_barchart_specific_group.R"
  # Alfa-Diversity
  alpha_calc: "scripts/04_alpha_diversity.R"
  alpha_plot: "scripts/04_alpha_plots.R"
  # Beta-Diversity
  beta_calc: "scripts/05_beta_diversity_calc.R"
  beta_vis_basic: "scripts/05_beta_diversity_visualisation.R"
  beta_vis_pca: "scripts/05_beta_advanced_vis_PCA.R"
  beta_vis_pcoa: "scripts/05_beta_advanced_vis_PCoA.R"
  # LinDA analysis
  linda_prepare: "scripts/06_preparing_object_for_Linda.R"
  linda_plot: "scripts/06_differential_abundance_LinDA.R"
  #Tax4Fun analysis
  tax4fun_object_generation: "scripts/09_Tax4Fun_object_generation.R"

### Parameters used to prepare the dataset before analysis and figure generation.
analysis_params:
  unclassified_label: "Unclassified"
  metadata_sep: "\t"
  metadata_dec: ","

filtering:  # <--- This is the 'Parent' box for Section 2
  samples_to_remove: ["CW_1", "CW_2","CW_3", "CW_4", "CW_5", "CW_6", "CW_7", "CW_8"]
  prev_filter_threshold: 3
  abund_filter_threshold: 5
  apply_prevalence: true
  apply_abundance: true

variance_filtering:
  cutoff: 0.00
  apply_filter: true 

subsetting:
  use_subset: true
  column_name: "CW_number"
  target_value: "CW_1"

### 3.0 Community barcharts parameters
Barplot_specific:
  palette_choice: "pals::kelly" #pals::polychrome       pals::kelly    pals::stepped"
  
  # Section 3.1: Global Community Barplots
  global_barplots:
    high_level: "phylum"
    low_level:  "class"
    facet_var: "MF_number"
    threshold: 0.5 #
    fig_width: 10
    fig_height: 8
    dpi: 300

  # Section 3.2: Specific Group Focus
  focus_barplot:
    target_rank: "order"
    target_val: "Burkholderiales_2"
    high_level: "family"
    low_level: "genus"
    facet_var: "Sample"
    threshold: 0.5
    fig_width: 12
    fig_height: 8
    dpi: 300
### 4.0 Alpha Diversity: Community Trait Analysis
Alpha_Diversity:
  # Pillar Selection
  traits:
    richness: ['chao1'] #'observed',
    dominance: ['dbp'] # 'absolute',
    evenness: ['pielou']
    information: ['shannon']
  
  # Plotting Configuration
  plotting:
    x_axis: "MF_number"
    color_by: "sample_depth_information"
    grid_cols: 2
    fig_width: 12
    fig_height: 8
    dpi: 300
    # Use 'all' to plot everything, or a specific list like ['observed', 'shannon']
    selected_metrics: "all"
### 5.0 Beta Diversity: Community Trait Analysis
Beta_Diversity:
  # Global Plotting Settings
  color_var: "MF_number" #Sample_depth_information
  shape_var: "sample_depth_information"
  show_ellipses: false
  show_labels: true
  labels: "timepoint_MF_number" #Timepoint
  group_clustering: "sample_depth_information"
  specified_permanova_formula: ["sample_depth_information" , "concentration_BTEX_ug_l", "phosphorus_total", "redoxpot"]
  fig_width: 12
  fig_height: 8

  # Section 5.1: Basic Ordination
  basic:
    metric: "wunifrac" # Options: aitchison, bray, jaccard, unifrac, wunifrac
    clr_variant: "BMR"

  # Section 5.2 & 5.3: Advanced (Vectors/Environmental Fit)
  advanced:
    numeric_env_variables: ["concentration_BTEX_ug_l", "phosphorus_total", "redoxpot", "pH", "EGV3", "iron2_TOTAL_mmoles_e_l__sulfate_relative_to_1D_flow", "sulfate_consumption_1D_flow_mmols_e_l_no_negatives", "manganese2_electron_acceptor_capacity_mmol_e_l"] #["iron2", "phosphorus_total", "concentration_BTEX", "sulfate"]
    categ_env_variables: ["timepoint", "sample_depth_information", "electron_balance_1D_flow", "dominant_electron_acceptor_species_1D_flow"] # ["Timepoint", "Sample_depth_information", "CW_Number"]
    top_asv_n: 20
    target_level: "family"
    filter_taxon_loadings: true
    filter_taxon_abundance_filter: 0.005
    filter_taxon_min_samples: 3 # Now you define the absolute number of samples in which the taxon should be found
    # Scaling for PCA
    pca_arrow_taxa: 1
    pca_arrow_env: 2
      # Section 5.2 & 5.3: Advanced (Vectors/Environmental Fit)
  advanced_for_rda:
    numeric_env_variables: ["concentration_BTEX_ug_l", "naphthalene_PAH_ug_l", "iron2_TOTAL_mmoles_e_l__sulfate_relative_to_1D_flow", "sulfate_consumption_1D_flow_mmols_e_l_no_negatives", "manganese2_electron_acceptor_capacity_mmol_e_l",
    "electron_acceptor_capacity_mmol_e_consumed_rel_to_1D_flow", "manganese2_mg_l", "iron2_mg_l","sulfate_mg_l", "electron_donor_acceptor_balance_BTEXN_PAH_acceptors_consumed_relative_to_1D_flow"] #["iron2", "phosphorus_total", "concentration_BTEX", "sulfate"]
    categ_env_variables: ["timepoint", "sample_depth_information", "CW_number", "electron_balance_1D_flow", "dominant_electron_acceptor_species_1D_flow"] # ["Timepoint", "Sample_depth_information", "CW_Number"]
    top_asv_n: 0
    target_tax_level: "family"
    
    
### 6.0 LinDA
Differential_Abundance:
  target_level: "family" 
  numeric_env_variables: ["concentration_BTEX_ug_l", "phosphorus_total", "redoxpot", "pH", "EGV3", "naphthalene_PAH_ug_l", "iron2_TOTAL_mmoles_e_l__sulfate_relative_to_1D_flow", "sulfate_consumption_1D_flow_mmols_e_l_no_negatives", "manganese2_electron_acceptor_capacity_mmol_e_l",
    "electron_acceptor_capacity_mmol_e_consumed_rel_to_1D_flow", "manganese2_mg_l", "iron2_mg_l", "sulfate_mg_l","time_continuous", "electron_donor_acceptor_balance_BTEXN_PAH_acceptors_consumed_relative_to_1D_flow"]
  categ_env_variables: ["timepoint", "CW_number", "CW_number_MF_number" , "sample_depth_information", "electron_balance_1D_flow", "dominant_electron_acceptor_species_1D_flow"]
  # Model Configuration
  model:
    main_var: "CW_number_MF_number"
    ref_group: "CW_3_MF09"
    # Note: Use double quotes for the formula to handle special characters
    formula: "~ CW_number_MF_number"

  # LinDA Algorithmic Parameters
  params:
    prev_filter: 0.05
    is.winsor: "TRUE"
    outlier_pct: 0.03
    zero_handling: "imputation"
    pseudo_cnt: 0.5
    alpha: 0.01
    p_adj_method: "BH"

  # Visualization
  plotting:
    var_to_plot: "CW_number_MF_numberCW_3_MF05" # Must match one of names(linda_res$output)
    fig_width: 12
    fig_height: 12
    
    #time_continuous , sample_depth_information0.60-0.80